# Generated by Django 5.2.7 on 2025-11-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_create_products_invoices'),
    ]

    operations = [
    ]
