# Generated by Django 5.2.7 on 2025-11-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='client',
            name='enterprise',
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_enterprise_document',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_taxpayer',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería')], default='DNI', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('created_by', 'document_number'), name='unique_user_document'),
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
