# Generated by Django 5.2.7 on 2025-11-06 06:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_manual_tables_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('client_ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC/DNI del Cliente')),
                ('client_address', models.TextField(blank=True, null=True, verbose_name='Dirección del Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impuesto')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envío')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('status', models.CharField(choices=[('DRAFT', '✏️ Borrador'), ('SENT', '📤 Enviada'), ('PAID', '✅ Pagada'), ('OVERDUE', '⚠️ Vencida'), ('CANCELLED', '❌ Cancelada'), ('REFUNDED', '🔄 Reembolsada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', '💵 Efectivo'), ('CARD', '💳 Tarjeta'), ('TRANSFER', '🏦 Transferencia'), ('CHECK', '📄 Cheque'), ('DIGITAL_WALLET', '📱 Billetera Digital'), ('OTHER', '📋 Otro')], default='CASH', max_length=20, verbose_name='Método de Pago')),
                ('currency', models.CharField(choices=[('PEN', 'S/ - Sol Peruano'), ('USD', '$ - Dólar Americano'), ('EUR', '€ - Euro')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tipo de Cambio')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='Términos de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU/Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo')),
                ('category', models.CharField(choices=[('PRODUCT', '📦 Producto Físico'), ('SERVICE', '🛠️ Servicio'), ('DIGITAL', '💻 Producto Digital'), ('SUBSCRIPTION', '🔄 Suscripción'), ('OTHER', '📋 Otro')], default='PRODUCT', max_length=20, verbose_name='Categoría')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Imagen')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensiones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_products', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enterprise.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre/Razón Social')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería'), ('PASSPORT', 'Pasaporte')], default='DNI', max_length=10, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(default='Perú', max_length=100, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_clients', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['created_by', 'document_number'], name='enterprise__created_66a298_idx'), models.Index(fields=['name'], name='enterprise__name_48d6e5_idx'), models.Index(fields=['document_number'], name='enterprise__documen_14146d_idx')],
                'unique_together': {('created_by', 'document_number')},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='enterprise__user_id_3e3783_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='enterprise__invoice_6bf64a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_name'], name='enterprise__client__dec8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='enterprise__issue_d_fdff49_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='enterprise__due_dat_676cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active'], name='enterprise__user_id_191fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='enterprise__categor_5d792e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='enterprise__sku_c94996_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='enterprise__created_3276de_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product'], name='enterprise__invoice_e3a69a_idx'),
        ),
    ]
