# Generated by Django 5.2.7 on 2025-10-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='record_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Registros'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('ADMIN', 'Administrador')], default='USER', max_length=10, verbose_name='Rol de Usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('FREE', 'Gratis'), ('PREMIUM', 'Premium')], default='FREE', max_length=10, verbose_name='Estado de Suscripción'),
        ),
    ]
