# Generated by Django 5.2.7 on 2025-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_record_count_user_role_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='record_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('ADMIN', 'Administrador')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('FREE', 'Gratis'), ('PREMIUM', 'Premium')], default='FREE', max_length=10),
        ),
    ]
