# Generated by Django 5.2.7 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_record_count_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_limits',
            field=models.JSONField(blank=True, help_text='Límites personalizados que sobrescriben los del plan. Formato JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('FREE', 'Gratis'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='core_transa_user_id_190a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='core_transa_user_id_103c58_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='core_transa_user_id_30a247_idx'),
        ),
    ]
