# Generated by Django 5.2.7 on 2025-11-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_product_invoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
